import type { Scene } from '../shared/types'

export const scenes: Scene[] = [
  {
    id: 'agentic-1',
    windowType: 'terminal',
    windowProps: {
      title: 'claude — research-workspace',
      lines: [
        { text: 'claude "Indian Ocean SST trend analysis and generate report"', type: 'command' },
        { text: '', type: 'output' },
        { text: 'Analyzing request...', type: 'output' },
        { text: 'Scanning project context: CLAUDE.md, directory structure', type: 'output' },
        { text: 'Found: /research/IndianOcean/ (6 subdirectories)', type: 'success' },
        { text: 'Found: plotting.toml (visualization guidelines)', type: 'success' },
        { text: 'Identified research domain: Physical Oceanography', type: 'success' },
      ],
    },
    bubble: {
      speaker: 'ai',
      text: 'Received a research request. Scanning the project context and CLAUDE.md rules first.',
    },
    duration: 4500,
  },
  {
    id: 'agentic-2',
    windowType: 'code',
    windowProps: {
      fileName: 'CLAUDE.md',
      language: 'markdown',
      code: `# Project Instructions

## Visualization Rules
- All fonts in English
- No border lines on maps
- Lat/Lon margin: 2 degrees beyond data extent
- Use PlotManager for every figure

## Project Structure
- 01_data/    → Raw & processed data
- 02_src/     → Analysis scripts
- 03_notebooks/ → Jupyter notebooks
- 04_results/ → Figures & analysis.md
- 05_papers/  → Manuscripts`,
      highlightLines: [4, 5, 6, 7],
    },
    bubble: {
      speaker: 'ai',
      text: 'Reading CLAUDE.md to understand project conventions — visualization rules, directory structure, and coding standards.',
    },
    duration: 4500,
  },
  {
    id: 'agentic-3',
    windowType: 'terminal',
    windowProps: {
      title: 'claude — task planning',
      lines: [
        { text: 'Decomposing complex task into subtasks...', type: 'comment' },
        { text: '', type: 'output' },
        { text: 'TodoWrite: Creating task plan', type: 'command' },
        { text: '  [1/4] Load NetCDF data with chunking (xarray + dask)', type: 'output' },
        { text: '  [2/4] SST time-series trend analysis (linear regression)', type: 'output' },
        { text: '  [3/4] Spatial distribution visualization (cartopy)', type: 'output' },
        { text: '  [4/4] Generate analysis report (markdown)', type: 'output' },
        { text: '', type: 'output' },
        { text: '4 tasks created. Starting sequential execution...', type: 'success' },
      ],
    },
    bubble: {
      speaker: 'ai',
      text: 'Decomposing the complex request into 4 subtasks with proper execution order.',
    },
    duration: 4000,
  },
  {
    id: 'agentic-4',
    windowType: 'terminal',
    windowProps: {
      title: 'claude — tool orchestration',
      lines: [
        { text: 'Multi-tool parallel execution', type: 'comment' },
        { text: '', type: 'output' },
        { text: '[Bash]      xarray chunked load: 3,652 timesteps, 720x1440 grid', type: 'output' },
        { text: '[Bash]      Linear regression: +0.18C/decade (p<0.01)', type: 'success' },
        { text: '[WebSearch] Found 5 references (Roxy et al. 2024...)', type: 'success' },
        { text: '[Grep]      Existing analysis patterns identified', type: 'output' },
        { text: '[MCP]       Plot saved: 04_results/fig01_sst_trend/', type: 'success' },
        { text: '[MCP]       analysis.md created for figure documentation', type: 'success' },
        { text: '', type: 'output' },
        { text: 'All 6 tool invocations completed in parallel', type: 'success' },
      ],
    },
    bubble: {
      speaker: 'system',
      text: 'Orchestrating 6 tools in parallel — Bash, WebSearch, Grep, MCP — to maximize throughput.',
    },
    duration: 5000,
  },
  {
    id: 'agentic-5',
    windowType: 'document',
    windowProps: {
      title: 'indian_ocean_sst_analysis.md',
      content: `# Indian Ocean SST Trend Analysis Report

## 1. Data Overview
- **Period**: 2015-2025 (11 years)
- **Source**: CMEMS Global Ocean SST (0.25 deg)
- **Grid**: 720 x 1440 (5.8M data points)

## 2. Key Findings
- **Trend**: +0.18 C/decade (p < 0.01, Mann-Kendall)
- **IOD influence**: Significant east-west dipole pattern
- **Seasonal peak**: March-April warming intensified

## 3. Spatial Pattern
- Western IO: Strongest warming (+0.22 C/decade)
- Eastern IO: Moderate warming (+0.14 C/decade)
- Equatorial belt: IOD-modulated variability

## 4. References
- Roxy et al. (2024) Nature Climate Change
- Wang et al. (2023) J. Climate

---
> Generated by Agentic AI | 4 tasks | 6 tools | 2,450 words`,
    },
    bubble: {
      speaker: 'ai',
      text: 'All tasks complete! Report generated with data analysis, visualizations, and references — ready for review.',
    },
    duration: 4000,
  },
]
