import type { Scene } from '../shared/types'

export const scenes: Scene[] = [
  {
    id: 'multi-1',
    windowType: 'terminal',
    windowProps: {
      title: 'orchestrator — planning',
      lines: [
        { text: 'Multi-Agent System activated', type: 'comment' },
        { text: '', type: 'output' },
        { text: 'Orchestrator -> Planner Agent', type: 'command' },
        { text: '', type: 'output' },
        { text: 'Goal: Analyze SST-fishery correlation in Indian Ocean', type: 'output' },
        { text: '', type: 'output' },
        { text: 'Research Plan (4 stages):', type: 'output' },
        { text: '  Stage 1: Collect SST + fishery + climate data', type: 'output' },
        { text: '  Stage 2: Statistical analysis & correlation', type: 'output' },
        { text: '  Stage 3: Synthesize findings into report', type: 'output' },
        { text: '  Stage 4: Human review & approval', type: 'output' },
        { text: '', type: 'output' },
        { text: 'Plan approved. Dispatching to agents...', type: 'success' },
      ],
    },
    bubble: {
      speaker: 'ai',
      text: 'Orchestrator activates the Planner agent — 4-stage research plan established.',
    },
    duration: 4500,
  },
  {
    id: 'multi-2',
    windowType: 'terminal',
    windowProps: {
      title: 'data-fetcher — parallel collection',
      lines: [
        { text: 'DataFetcher Agent: 3 sources in parallel', type: 'comment' },
        { text: '', type: 'output' },
        { text: '[Thread-1] Copernicus CMEMS SST query...', type: 'output' },
        { text: '[Thread-2] FAO FishStatJ database query...', type: 'output' },
        { text: '[Thread-3] NOAA Climate indices (IOD, ENSO)...', type: 'output' },
        { text: '', type: 'output' },
        { text: '[Thread-1] SST: 4,015 monthly grids collected', type: 'success' },
        { text: '[Thread-2] Fishery: 12 species, 2010-2024 catch data', type: 'success' },
        { text: '[Thread-3] Climate: IOD/ENSO indices downloaded', type: 'success' },
        { text: '', type: 'output' },
        { text: 'All 3 sources collected. Passing to Synthesizer...', type: 'success' },
      ],
    },
    bubble: {
      speaker: 'ai',
      text: 'Data Fetcher agent collects from 3 sources in parallel — SST, fishery stats, and climate indices.',
    },
    duration: 4500,
  },
  {
    id: 'multi-3',
    windowType: 'code',
    windowProps: {
      fileName: 'synthesizer_analysis.py',
      language: 'python',
      code: `import pandas as pd
import numpy as np
from scipy.stats import pearsonr, spearmanr

# Merge datasets on time dimension
merged = pd.merge(sst_monthly, fishery_catch, on="date")
merged = pd.merge(merged, climate_idx, on="date")

# Pearson correlation: SST vs total catch
r_sst, p_sst = pearsonr(merged.sst_mean, merged.total_catch)
print(f"SST-Catch: r={r_sst:.2f}, p={p_sst:.4f}")

# IOD modulation analysis
iod_pos = merged[merged.iod > 0.4]
iod_neg = merged[merged.iod < -0.4]
print(f"IOD+ catch: {iod_pos.total_catch.mean():.0f}")
print(f"IOD- catch: {iod_neg.total_catch.mean():.0f}")

# Result: r=0.78, p<0.001 (strong positive)`,
      highlightLines: [10, 11, 19],
    },
    bubble: {
      speaker: 'ai',
      text: 'Synthesizer agent finds strong positive correlation (r=0.78) — SST significantly affects fishery catch.',
    },
    duration: 5000,
  },
  {
    id: 'multi-4',
    windowType: 'document',
    windowProps: {
      title: 'SST-Fishery Correlation Report',
      content: `# Indian Ocean SST-Fishery Correlation Analysis

## Executive Summary
Strong positive correlation (r=0.78, p<0.001) found between SST and total fishery catch in the Indian Ocean.

## Key Findings
- **Primary**: SST increase of 1C corresponds to 15% higher catch
- **IOD Modulation**: Positive IOD years show 23% higher catch
- **Species-specific**: Tuna species most responsive (r=0.84)
- **Seasonal**: March-May peak correlation

## Data Sources
- SST: Copernicus CMEMS (4,015 monthly grids)
- Fishery: FAO FishStatJ (12 species, 2010-2024)
- Climate: NOAA IOD/ENSO indices

## Statistical Methods
- Pearson/Spearman correlation
- IOD-stratified analysis
- Seasonal decomposition

---
> Report generated by Multi-Agent Synthesizer`,
    },
    bubble: {
      speaker: 'ai',
      text: 'Report Generator agent structures findings into a formal analysis report with methodology.',
    },
    duration: 4500,
  },
  {
    id: 'multi-5',
    windowType: 'browser',
    windowProps: {
      url: 'http://localhost:3000/review/report-2025-001',
      title: 'Human Review Portal',
      content: `## Report Review — SST-Fishery Correlation

### Status: Awaiting Approval

### Reviewer Checklist
- **Data quality**: Sources verified (Copernicus, FAO, NOAA)
- **Statistics**: Correlation significant (p<0.001)
- **Methodology**: Appropriate for the research question
- **Completeness**: All 12 species analyzed

### Agent Collaboration Summary
- **Planner**: 4-stage research plan
- **DataFetcher**: 3 parallel data sources
- **Synthesizer**: Statistical analysis (r=0.78)
- **ReportGen**: Structured report with references

---

> 4 AI agents collaborated to produce this report. Final human approval required.`,
    },
    bubble: {
      speaker: 'researcher',
      text: '4 AI agents collaborated on this analysis — now reviewing the final report for approval.',
    },
    duration: 4000,
  },
]
